export const TYPES = {
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  Application: Symbol.for('Application'),
  Database: Symbol.for('Database'),
  UserService: Symbol.for('UserService'),
  OfferService: Symbol.for('OfferService'),
  CityService: Symbol.for('CityService'),
  CommentService: Symbol.for('CommentService'),
  ImportService: Symbol.for('ImportService'),
  UserController: Symbol.for('UserController'),
  OfferController: Symbol.for('OfferController'),
  CommentController: Symbol.for('CommentController'),
  FavoritesController: Symbol.for('FavoritesController'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  ValidateObjectIdMiddleware: Symbol.for('ValidateObjectIdMiddleware'),
};
